[package]
name = "hsk-learn"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
tokio = { version = "1", features = ["full"] }
shuttle-runtime = "0.51"
shuttle-actix-web = "0.51"
shuttle-persist = "0.51"
