use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
pub struct CharAnnotation {
    pub ch: String,
    pub pinyin: String,
    pub english: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct ExtraWord {
    pub hanzi: String,
    pub pinyin: String,
    pub english: String,
}

#[derive(Debug, Clone, Serialize)]
pub struct StoryParagraph {
    pub chars: Vec<CharAnnotation>,
}

#[derive(Debug, Clone, Serialize)]
pub struct Story {
    pub id: u32,
    pub title: String,
    pub title_cn: String,
    pub description: String,
    pub extra_vocab: Vec<ExtraWord>,
    pub paragraphs: Vec<StoryParagraph>,
}

fn p(text: &str) -> String {
    text.to_string()
}

fn ch(ch: &str, pinyin: &str, english: &str) -> CharAnnotation {
    CharAnnotation {
        ch: ch.into(),
        pinyin: pinyin.into(),
        english: english.into(),
    }
}

fn para(chars: Vec<CharAnnotation>) -> StoryParagraph {
    StoryParagraph { chars }
}

fn extra(hanzi: &str, pinyin: &str, english: &str) -> ExtraWord {
    ExtraWord {
        hanzi: hanzi.into(),
        pinyin: pinyin.into(),
        english: english.into(),
    }
}

pub fn get_stories_meta() -> Vec<serde_json::Value> {
    get_all_stories()
        .iter()
        .map(|s| {
            serde_json::json!({
                "id": s.id,
                "title": s.title,
                "title_cn": s.title_cn,
                "description": s.description,
            })
        })
        .collect()
}

pub fn get_all_stories() -> Vec<Story> {
    vec![
        story_monkey_king(),
        story_mulan(),
        story_nian(),
        story_cowherd(),
        story_chang_e(),
        story_three_body_1(),
        story_three_body_2(),
        story_three_body_3(),
    ]
}

fn story_monkey_king() -> Story {
    Story {
        id: 1,
        title: p("The Monkey King"),
        title_cn: p("美猴王"),
        description: p("Sun Wukong is born from a stone and becomes king of the monkeys. Simplified from Journey to the West."),
        extra_vocab: vec![
            extra("猴", "hóu", "monkey"),
            extra("王", "wáng", "king"),
            extra("石头", "shítou", "stone, rock"),
            extra("山", "shān", "mountain"),
            extra("海", "hǎi", "sea, ocean"),
            extra("瀑布", "pùbù", "waterfall"),
            extra("洞", "dòng", "cave"),
            extra("跳", "tiào", "to jump"),
            extra("勇敢", "yǒnggǎn", "brave"),
            extra("成", "chéng", "to become"),
        ],
        paragraphs: vec![
            para(vec![
                ch("很", "hěn", "very"), ch("久", "jiǔ", "long time"), ch("很", "hěn", "very"), ch("久", "jiǔ", "long time"),
                ch("以", "yǐ", "before"), ch("前", "qián", "before"), ch("，", ",", ","),
                ch("在", "zài", "at"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("大", "dà", "big"), ch("山", "shān", "mountain"), ch("上", "shàng", "on"),  ch("，", ",", ","),
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("大", "dà", "big"), ch("石", "shí", "stone"), ch("头", "tou", "stone"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("天", "tiān", "day"), ch("，", ",", ","),
                ch("石", "shí", "stone"), ch("头", "tou", "stone"),
                ch("里", "lǐ", "inside"), ch("出", "chū", "come out"), ch("来", "lái", "come"),
                ch("了", "le", "completed"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("小", "xiǎo", "small"), ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"),
                ch("小", "xiǎo", "small"), ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"),
                ch("很", "hěn", "very"), ch("高", "gāo", "tall"), ch("兴", "xìng", "happy"), ch("。", ".", "."),
                ch("他", "tā", "he"), ch("看", "kàn", "to look"),
                ch("山", "shān", "mountain"), ch("，", ",", ","),
                ch("看", "kàn", "to look"), ch("水", "shuǐ", "water"), ch("，", ",", ","),
                ch("看", "kàn", "to look"), ch("花", "huā", "flower"), ch("，", ",", ","),
                ch("看", "kàn", "to look"), ch("树", "shù", "tree"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"), ch("去", "qù", "to go"),
                ch("找", "zhǎo", "to look for"),
                ch("别", "bié", "other"), ch("的", "de", "possessive"),
                ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"), ch("。", ".", "."),
                ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"), ch("们", "men", "plural"),
                ch("都", "dōu", "all"), ch("很", "hěn", "very"),
                ch("喜", "xǐ", "like"), ch("欢", "huān", "like"),
                ch("他", "tā", "him"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("天", "tiān", "day"), ch("，", ",", ","),
                ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"), ch("们", "men", "plural"),
                ch("找", "zhǎo", "to find"), ch("到", "dào", "arrive"),
                ch("了", "le", "completed"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("大", "dà", "big"), ch("瀑", "pù", "waterfall"), ch("布", "bù", "waterfall"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("谁", "shéi", "who"), ch("能", "néng", "can"),
                ch("跳", "tiào", "jump"), ch("进", "jìn", "enter"),
                ch("去", "qù", "go"), ch("？", "?", "?"),
                ch("谁", "shéi", "who"), ch("就", "jiù", "then"),
                ch("是", "shì", "is"),
                ch("我", "wǒ", "our"), ch("们", "men", "plural"), ch("的", "de", "possessive"),
                ch("王", "wáng", "king"), ch("！", "!", "!"),
            ]),
            para(vec![
                ch("小", "xiǎo", "small"), ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"),
                ch("很", "hěn", "very"), ch("勇", "yǒng", "brave"), ch("敢", "gǎn", "brave"), ch("。", ".", "."),
                ch("他", "tā", "he"), ch("跳", "tiào", "jump"),
                ch("进", "jìn", "enter"), ch("了", "le", "completed"),
                ch("瀑", "pù", "waterfall"), ch("布", "bù", "waterfall"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("里", "lǐ", "inside"), ch("面", "miàn", "side"),
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("很", "hěn", "very"), ch("大", "dà", "big"), ch("的", "de", "possessive"),
                ch("洞", "dòng", "cave"), ch("。", ".", "."),
                ch("有", "yǒu", "there is"),
                ch("桌", "zhuō", "table"), ch("子", "zi", "suffix"), ch("，", ",", ","),
                ch("有", "yǒu", "there is"),
                ch("椅", "yǐ", "chair"), ch("子", "zi", "suffix"), ch("，", ",", ","),
                ch("有", "yǒu", "there is"),
                ch("水", "shuǐ", "water"), ch("果", "guǒ", "fruit"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("小", "xiǎo", "small"), ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"),
                ch("出", "chū", "go out"), ch("来", "lái", "come"),
                ch("说", "shuō", "to say"), ch("：", ":", ":"),
                ch("“", "“", "quote"), ch("里", "lǐ", "inside"), ch("面", "miàn", "side"),
                ch("很", "hěn", "very"), ch("好", "hǎo", "good"), ch("！", "!", "!"),
                ch("我", "wǒ", "our"), ch("们", "men", "plural"),
                ch("都", "dōu", "all"), ch("可", "kě", "can"), ch("以", "yǐ", "can"),
                ch("住", "zhù", "to live"), ch("在", "zài", "at"),
                ch("那", "nà", "there"), ch("儿", "r", "there"), ch("！", "!", "!"), ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("猴", "hóu", "monkey"), ch("子", "zi", "suffix"), ch("们", "men", "plural"),
                ch("都", "dōu", "all"), ch("很", "hěn", "very"),
                ch("高", "gāo", "happy"), ch("兴", "xìng", "happy"), ch("。", ".", "."),
                ch("他", "tā", "they"), ch("们", "men", "plural"),
                ch("叫", "jiào", "to call"), ch("他", "tā", "him"),
                ch("“", "“", "quote"), ch("美", "měi", "beautiful"),
                ch("猴", "hóu", "monkey"), ch("王", "wáng", "king"), ch("“", "“", "quote"), ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_mulan() -> Story {
    Story {
        id: 2,
        title: p("Mulan Goes to War"),
        title_cn: p("花木兰"),
        description: p("A young woman takes her father's place in the army. Simplified from the Ballad of Mulan."),
        extra_vocab: vec![
            extra("木兰", "Mùlán", "Mulan (name)"),
            extra("军", "jūn", "army"),
            extra("战", "zhàn", "war, battle"),
            extra("马", "mǎ", "horse"),
            extra("父亲", "fùqīn", "father"),
            extra("勇敢", "yǒnggǎn", "brave"),
            extra("将军", "jiāngjūn", "general"),
            extra("打仗", "dǎzhàng", "to fight a war"),
            extra("回来", "huílái", "to come back"),
        ],
        paragraphs: vec![
            para(vec![
                ch("很", "hěn", "very"), ch("久", "jiǔ", "long time"),
                ch("以", "yǐ", "before"), ch("前", "qián", "before"), ch("，", ",", ","),
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("女", "nǚ", "female"), ch("孩", "hái", "child"), ch("子", "zi", "suffix"), ch("，", ",", ","),
                ch("她", "tā", "she"), ch("叫", "jiào", "called"),
                ch("木", "Mù", "Mulan"), ch("兰", "lán", "Mulan"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("木", "Mù", "Mulan"), ch("兰", "lán", "Mulan"), ch("的", "de", "possessive"),
                ch("父", "fù", "father"), ch("亲", "qīn", "father"),
                ch("很", "hěn", "very"), ch("老", "lǎo", "old"),
                ch("了", "le", "already"), ch("，", ",", ","),
                ch("身", "shēn", "body"), ch("体", "tǐ", "body"),
                ch("不", "bù", "not"), ch("好", "hǎo", "good"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("有", "yǒu", "there is"), ch("一", "yī", "one"), ch("天", "tiān", "day"), ch("，", ",", ","),
                ch("将", "jiāng", "general"), ch("军", "jūn", "general"),
                ch("说", "shuō", "to say"), ch("：", ":", ":"),
                ch("“", "“", "quote"),
                ch("每", "měi", "every"), ch("家", "jiā", "family"),
                ch("要", "yào", "must"),
                ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("人", "rén", "person"),
                ch("去", "qù", "to go"), ch("打", "dǎ", "to fight"),
                ch("仗", "zhàng", "war"), ch("。", ".", "."), ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("木", "Mù", "Mulan"), ch("兰", "lán", "Mulan"),
                ch("对", "duì", "to"), ch("父", "fù", "father"), ch("亲", "qīn", "father"),
                ch("说", "shuō", "to say"), ch("：", ":", ":"),
                ch("“", "“", "quote"),
                ch("爸", "bà", "dad"), ch("爸", "ba", "dad"), ch("，", ",", ","),
                ch("你", "nǐ", "you"), ch("不", "bù", "not"),
                ch("能", "néng", "can"), ch("去", "qù", "to go"), ch("。", ".", "."),
                ch("我", "wǒ", "I"), ch("去", "qù", "to go"), ch("！", "!", "!"),
                ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("她", "tā", "she"), ch("穿", "chuān", "to wear"),
                ch("了", "le", "completed"),
                ch("父", "fù", "father"), ch("亲", "qīn", "father"), ch("的", "de", "possessive"),
                ch("衣", "yī", "clothes"), ch("服", "fu", "clothes"), ch("，", ",", ","),
                ch("买", "mǎi", "to buy"), ch("了", "le", "completed"),
                ch("一", "yī", "one"), ch("匹", "pǐ", "measure word"),
                ch("马", "mǎ", "horse"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("木", "Mù", "Mulan"), ch("兰", "lán", "Mulan"),
                ch("很", "hěn", "very"), ch("勇", "yǒng", "brave"), ch("敢", "gǎn", "brave"), ch("。", ".", "."),
                ch("她", "tā", "she"), ch("打", "dǎ", "to fight"),
                ch("了", "le", "completed"),
                ch("很", "hěn", "very"), ch("多", "duō", "many"),
                ch("年", "nián", "year"), ch("的", "de", "possessive"),
                ch("仗", "zhàng", "war"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("战", "zhàn", "war"), ch("争", "zhēng", "war"),
                ch("完", "wán", "finished"), ch("了", "le", "completed"), ch("。", ".", "."),
                ch("将", "jiāng", "general"), ch("军", "jūn", "general"),
                ch("说", "shuō", "to say"), ch("：", ":", ":"),
                ch("“", "“", "quote"),
                ch("你", "nǐ", "you"), ch("想", "xiǎng", "to want"),
                ch("要", "yào", "to want"), ch("什", "shén", "what"), ch("么", "me", "what"), ch("？", "?", "?"),
                ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("木", "Mù", "Mulan"), ch("兰", "lán", "Mulan"),
                ch("说", "shuō", "to say"), ch("：", ":", ":"),
                ch("“", "“", "quote"),
                ch("我", "wǒ", "I"), ch("想", "xiǎng", "to want"),
                ch("回", "huí", "to return"), ch("家", "jiā", "home"), ch("。", ".", "."),
                ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("她", "tā", "she"), ch("回", "huí", "to return"),
                ch("到", "dào", "arrive"), ch("了", "le", "completed"),
                ch("家", "jiā", "home"), ch("，", ",", ","),
                ch("穿", "chuān", "to wear"), ch("了", "le", "completed"),
                ch("漂", "piào", "beautiful"), ch("亮", "liang", "beautiful"),
                ch("的", "de", "possessive"), ch("衣", "yī", "clothes"), ch("服", "fu", "clothes"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("朋", "péng", "friend"), ch("友", "yǒu", "friend"), ch("们", "men", "plural"),
                ch("都", "dōu", "all"), ch("很", "hěn", "very"),
                ch("高", "gāo", "happy"), ch("兴", "xìng", "happy"),
                ch("她", "tā", "she"), ch("回", "huí", "return"),
                ch("来", "lái", "come"), ch("了", "le", "completed"), ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_nian() -> Story {
    Story {
        id: 3,
        title: p("The Monster Nian"),
        title_cn: p("年兽"),
        description: p(
            "Why Chinese New Year has fireworks and red decorations. A classic folk tale.",
        ),
        extra_vocab: vec![
            extra("兽", "shòu", "beast, monster"),
            extra("怕", "pà", "to be afraid of"),
            extra("红色", "hóngsè", "red color"),
            extra("声音", "shēngyīn", "sound"),
            extra("村子", "cūnzi", "village"),
            extra("跑", "pǎo", "to run"),
            extra("放", "fàng", "to set off"),
            extra("鞭炮", "biānpào", "firecrackers"),
            extra("过年", "guònián", "celebrate New Year"),
        ],
        paragraphs: vec![
            para(vec![
                ch("很", "hěn", "very"),
                ch("久", "jiǔ", "long time"),
                ch("以", "yǐ", "before"),
                ch("前", "qián", "before"),
                ch("，", ",", ","),
                ch("有", "yǒu", "there is"),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("大", "dà", "big"),
                ch("兽", "shòu", "beast"),
                ch("，", ",", ","),
                ch("他", "tā", "it"),
                ch("叫", "jiào", "called"),
                ch("“", "“", "quote"),
                ch("年", "nián", "Nian"),
                ch("“", "“", "quote"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("冬", "dōng", "winter"),
                ch("天", "tiān", "day"),
                ch("，", ",", ","),
                ch("年", "nián", "Nian"),
                ch("都", "dōu", "always"),
                ch("来", "lái", "to come"),
                ch("村", "cūn", "village"),
                ch("子", "zi", "suffix"),
                ch("里", "lǐ", "inside"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("很", "hěn", "very"),
                ch("怕", "pà", "afraid"),
                ch("他", "tā", "it"),
                ch("。", ".", "."),
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("他", "tā", "they"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("跑", "pǎo", "to run"),
                ch("到", "dào", "to"),
                ch("山", "shān", "mountain"),
                ch("上", "shàng", "on"),
                ch("去", "qù", "to go"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("有", "yǒu", "there is"),
                ch("一", "yī", "one"),
                ch("天", "tiān", "day"),
                ch("，", ",", ","),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("老", "lǎo", "old"),
                ch("人", "rén", "person"),
                ch("来", "lái", "to come"),
                ch("了", "le", "completed"),
                ch("。", ".", "."),
                ch("他", "tā", "he"),
                ch("说", "shuō", "to say"),
                ch("：", ":", ":"),
                ch("“", "“", "quote"),
                ch("我", "wǒ", "I"),
                ch("知", "zhī", "to know"),
                ch("道", "dào", "to know"),
                ch("年", "nián", "Nian"),
                ch("怕", "pà", "afraid of"),
                ch("什", "shén", "what"),
                ch("么", "me", "what"),
                ch("。", ".", "."),
                ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("“", "“", "quote"),
                ch("年", "nián", "Nian"),
                ch("怕", "pà", "afraid of"),
                ch("红", "hóng", "red"),
                ch("色", "sè", "color"),
                ch("，", ",", ","),
                ch("怕", "pà", "afraid of"),
                ch("大", "dà", "big"),
                ch("的", "de", "possessive"),
                ch("声", "shēng", "sound"),
                ch("音", "yīn", "sound"),
                ch("！", "!", "!"),
                ch("“", "“", "quote"),
            ]),
            para(vec![
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("在", "zài", "at"),
                ch("门", "mén", "door"),
                ch("上", "shàng", "on"),
                ch("放", "fàng", "to put"),
                ch("了", "le", "completed"),
                ch("红", "hóng", "red"),
                ch("色", "sè", "color"),
                ch("的", "de", "possessive"),
                ch("东", "dōng", "thing"),
                ch("西", "xi", "thing"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "they"),
                ch("们", "men", "plural"),
                ch("还", "hái", "also"),
                ch("放", "fàng", "to set off"),
                ch("了", "le", "completed"),
                ch("鞭", "biān", "firecracker"),
                ch("炮", "pào", "firecracker"),
                ch("。", ".", "."),
                ch("声", "shēng", "sound"),
                ch("音", "yīn", "sound"),
                ch("很", "hěn", "very"),
                ch("大", "dà", "big"),
                ch("！", "!", "!"),
            ]),
            para(vec![
                ch("年", "nián", "Nian"),
                ch("来", "lái", "to come"),
                ch("了", "le", "completed"),
                ch("。", ".", "."),
                ch("他", "tā", "it"),
                ch("看", "kàn", "to see"),
                ch("到", "dào", "to"),
                ch("红", "hóng", "red"),
                ch("色", "sè", "color"),
                ch("，", ",", ","),
                ch("听", "tīng", "to hear"),
                ch("到", "dào", "to"),
                ch("大", "dà", "big"),
                ch("声", "shēng", "sound"),
                ch("音", "yīn", "sound"),
                ch("，", ",", ","),
                ch("很", "hěn", "very"),
                ch("怕", "pà", "afraid"),
                ch("！", "!", "!"),
            ]),
            para(vec![
                ch("年", "nián", "Nian"),
                ch("跑", "pǎo", "to run"),
                ch("了", "le", "completed"),
                ch("！", "!", "!"),
                ch("他", "tā", "it"),
                ch("再", "zài", "again"),
                ch("也", "yě", "also"),
                ch("没", "méi", "not"),
                ch("有", "yǒu", "have"),
                ch("回", "huí", "to return"),
                ch("来", "lái", "come"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("从", "cóng", "from"),
                ch("那", "nà", "that"),
                ch("以", "yǐ", "after"),
                ch("后", "hòu", "after"),
                ch("，", ",", ","),
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("过", "guò", "to celebrate"),
                ch("年", "nián", "New Year"),
                ch("，", ",", ","),
                ch("放", "fàng", "to set off"),
                ch("鞭", "biān", "firecracker"),
                ch("炮", "pào", "firecracker"),
                ch("，", ",", ","),
                ch("穿", "chuān", "to wear"),
                ch("红", "hóng", "red"),
                ch("衣", "yī", "clothes"),
                ch("服", "fu", "clothes"),
                ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_cowherd() -> Story {
    Story {
        id: 4,
        title: p("The Cowherd and the Weaver Girl"),
        title_cn: p("牛郎织女"),
        description: p("A love story written in the stars. The origin of the Qixi Festival."),
        extra_vocab: vec![
            extra("牛郎", "Niúláng", "Cowherd (name)"),
            extra("织女", "Zhīnǚ", "Weaver Girl (name)"),
            extra("牛", "niú", "cow, ox"),
            extra("天", "tiān", "sky, heaven"),
            extra("河", "hé", "river"),
            extra("星", "xīng", "star"),
            extra("爱", "ài", "to love"),
            extra("哭", "kū", "to cry"),
        ],
        paragraphs: vec![
            para(vec![
                ch("牛", "Niú", "Cowherd"),
                ch("郎", "láng", "Cowherd"),
                ch("是", "shì", "is"),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("很", "hěn", "very"),
                ch("好", "hǎo", "good"),
                ch("的", "de", "possessive"),
                ch("男", "nán", "male"),
                ch("人", "rén", "person"),
                ch("。", ".", "."),
                ch("他", "tā", "he"),
                ch("没", "méi", "not"),
                ch("有", "yǒu", "have"),
                ch("爸", "bà", "dad"),
                ch("爸", "ba", "dad"),
                ch("妈", "mā", "mom"),
                ch("妈", "ma", "mom"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"),
                ch("有", "yǒu", "have"),
                ch("一", "yī", "one"),
                ch("头", "tóu", "measure word"),
                ch("老", "lǎo", "old"),
                ch("牛", "niú", "cow"),
                ch("。", ".", "."),
                ch("老", "lǎo", "old"),
                ch("牛", "niú", "cow"),
                ch("是", "shì", "is"),
                ch("他", "tā", "his"),
                ch("最", "zuì", "most"),
                ch("好", "hǎo", "good"),
                ch("的", "de", "possessive"),
                ch("朋", "péng", "friend"),
                ch("友", "yǒu", "friend"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("织", "Zhī", "Weaver"),
                ch("女", "nǚ", "Girl"),
                ch("住", "zhù", "to live"),
                ch("在", "zài", "at"),
                ch("天", "tiān", "sky"),
                ch("上", "shàng", "above"),
                ch("。", ".", "."),
                ch("她", "tā", "she"),
                ch("很", "hěn", "very"),
                ch("漂", "piào", "beautiful"),
                ch("亮", "liang", "beautiful"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("有", "yǒu", "there is"),
                ch("一", "yī", "one"),
                ch("天", "tiān", "day"),
                ch("，", ",", ","),
                ch("织", "Zhī", "Weaver"),
                ch("女", "nǚ", "Girl"),
                ch("来", "lái", "to come"),
                ch("到", "dào", "arrive"),
                ch("了", "le", "completed"),
                ch("人", "rén", "people"),
                ch("的", "de", "possessive"),
                ch("家", "jiā", "home"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("牛", "Niú", "Cowherd"),
                ch("郎", "láng", "Cowherd"),
                ch("和", "hé", "and"),
                ch("织", "Zhī", "Weaver"),
                ch("女", "nǚ", "Girl"),
                ch("很", "hěn", "very"),
                ch("喜", "xǐ", "like"),
                ch("欢", "huān", "like"),
                ch("对", "duì", "each"),
                ch("方", "fāng", "other"),
                ch("。", ".", "."),
                ch("他", "tā", "they"),
                ch("们", "men", "plural"),
                ch("有", "yǒu", "have"),
                ch("了", "le", "completed"),
                ch("两", "liǎng", "two"),
                ch("个", "gè", "measure word"),
                ch("孩", "hái", "child"),
                ch("子", "zi", "suffix"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("但", "dàn", "but"),
                ch("是", "shì", "but"),
                ch("，", ",", ","),
                ch("天", "tiān", "heaven"),
                ch("上", "shàng", "above"),
                ch("的", "de", "possessive"),
                ch("王", "wáng", "king"),
                ch("不", "bù", "not"),
                ch("高", "gāo", "happy"),
                ch("兴", "xìng", "happy"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"),
                ch("让", "ràng", "to make"),
                ch("织", "Zhī", "Weaver"),
                ch("女", "nǚ", "Girl"),
                ch("回", "huí", "to return"),
                ch("天", "tiān", "sky"),
                ch("上", "shàng", "above"),
                ch("去", "qù", "to go"),
                ch("。", ".", "."),
                ch("在", "zài", "at"),
                ch("他", "tā", "them"),
                ch("们", "men", "plural"),
                ch("中", "zhōng", "middle"),
                ch("间", "jiān", "between"),
                ch("，", ",", ","),
                ch("有", "yǒu", "there is"),
                ch("一", "yī", "one"),
                ch("条", "tiáo", "measure word"),
                ch("大", "dà", "big"),
                ch("河", "hé", "river"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("牛", "Niú", "Cowherd"),
                ch("郎", "láng", "Cowherd"),
                ch("和", "hé", "and"),
                ch("孩", "hái", "child"),
                ch("子", "zi", "suffix"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("哭", "kū", "to cry"),
                ch("了", "le", "completed"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("七", "qī", "seven"),
                ch("月", "yuè", "month"),
                ch("七", "qī", "seven"),
                ch("日", "rì", "day"),
                ch("，", ",", ","),
                ch("很", "hěn", "very"),
                ch("多", "duō", "many"),
                ch("鸟", "niǎo", "bird"),
                ch("来", "lái", "to come"),
                ch("帮", "bāng", "to help"),
                ch("助", "zhù", "to help"),
                ch("他", "tā", "them"),
                ch("们", "men", "plural"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"),
                ch("一", "yī", "one"),
                ch("天", "tiān", "day"),
                ch("，", ",", ","),
                ch("牛", "Niú", "Cowherd"),
                ch("郎", "láng", "Cowherd"),
                ch("和", "hé", "and"),
                ch("织", "Zhī", "Weaver"),
                ch("女", "nǚ", "Girl"),
                ch("可", "kě", "can"),
                ch("以", "yǐ", "can"),
                ch("在", "zài", "at"),
                ch("一", "yì", "together"),
                ch("起", "qǐ", "together"),
                ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_chang_e() -> Story {
    Story {
        id: 5,
        title: p("Chang'e Flies to the Moon"),
        title_cn: p("嫦娥奔月"),
        description: p("The origin of the Mid-Autumn Festival. A woman flies to the moon."),
        extra_vocab: vec![
            extra("嫦娥", "Cháng'é", "Chang'e (name)"),
            extra("后羿", "Hòu Yì", "Hou Yi (name)"),
            extra("月亮", "yuèliang", "moon"),
            extra("药", "yào", "medicine"),
            extra("飞", "fēi", "to fly"),
            extra("坏", "huài", "bad"),
            extra("偷", "tōu", "to steal"),
        ],
        paragraphs: vec![
            para(vec![
                ch("很", "hěn", "very"),
                ch("久", "jiǔ", "long time"),
                ch("以", "yǐ", "before"),
                ch("前", "qián", "before"),
                ch("，", ",", ","),
                ch("天", "tiān", "sky"),
                ch("上", "shàng", "above"),
                ch("有", "yǒu", "there are"),
                ch("十", "shí", "ten"),
                ch("个", "gè", "measure word"),
                ch("太", "tài", "too"),
                ch("阳", "yáng", "sun"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("太", "tài", "too"),
                ch("热", "rè", "hot"),
                ch("了", "le", "completed"),
                ch("！", "!", "!"),
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("很", "hěn", "very"),
                ch("不", "bù", "not"),
                ch("高", "gāo", "happy"),
                ch("兴", "xìng", "happy"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("后", "Hòu", "Hou Yi"),
                ch("羿", "Yì", "Hou Yi"),
                ch("是", "shì", "is"),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("很", "hěn", "very"),
                ch("勇", "yǒng", "brave"),
                ch("敢", "gǎn", "brave"),
                ch("的", "de", "possessive"),
                ch("人", "rén", "person"),
                ch("。", ".", "."),
                ch("他", "tā", "he"),
                ch("把", "bǎ", "disposal"),
                ch("九", "jiǔ", "nine"),
                ch("个", "gè", "measure word"),
                ch("太", "tài", "too"),
                ch("阳", "yáng", "sun"),
                ch("打", "dǎ", "to hit"),
                ch("下", "xià", "down"),
                ch("来", "lái", "come"),
                ch("了", "le", "completed"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("都", "dōu", "all"),
                ch("很", "hěn", "very"),
                ch("高", "gāo", "happy"),
                ch("兴", "xìng", "happy"),
                ch("。", ".", "."),
                ch("他", "tā", "they"),
                ch("们", "men", "plural"),
                ch("给", "gěi", "to give"),
                ch("了", "le", "completed"),
                ch("后", "Hòu", "Hou Yi"),
                ch("羿", "Yì", "Hou Yi"),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("药", "yào", "medicine"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("吃", "chī", "to eat"),
                ch("了", "le", "completed"),
                ch("这", "zhè", "this"),
                ch("个", "gè", "measure word"),
                ch("药", "yào", "medicine"),
                ch("，", ",", ","),
                ch("就", "jiù", "then"),
                ch("可", "kě", "can"),
                ch("以", "yǐ", "can"),
                ch("飞", "fēi", "to fly"),
                ch("到", "dào", "to"),
                ch("天", "tiān", "sky"),
                ch("上", "shàng", "above"),
                ch("去", "qù", "to go"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("后", "Hòu", "Hou Yi"),
                ch("羿", "Yì", "Hou Yi"),
                ch("的", "de", "possessive"),
                ch("妻", "qī", "wife"),
                ch("子", "zi", "suffix"),
                ch("叫", "jiào", "called"),
                ch("嫦", "Cháng", "Chang'e"),
                ch("娥", "é", "Chang'e"),
                ch("。", ".", "."),
                ch("他", "tā", "he"),
                ch("不", "bù", "not"),
                ch("想", "xiǎng", "to want"),
                ch("吃", "chī", "to eat"),
                ch("药", "yào", "medicine"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("但", "dàn", "but"),
                ch("是", "shì", "but"),
                ch("，", ",", ","),
                ch("有", "yǒu", "there is"),
                ch("一", "yī", "one"),
                ch("个", "gè", "measure word"),
                ch("坏", "huài", "bad"),
                ch("人", "rén", "person"),
                ch("想", "xiǎng", "to want"),
                ch("偷", "tōu", "to steal"),
                ch("这", "zhè", "this"),
                ch("个", "gè", "measure word"),
                ch("药", "yào", "medicine"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("嫦", "Cháng", "Chang'e"),
                ch("娥", "é", "Chang'e"),
                ch("不", "bù", "not"),
                ch("想", "xiǎng", "to want"),
                ch("让", "ràng", "to let"),
                ch("坏", "huài", "bad"),
                ch("人", "rén", "person"),
                ch("吃", "chī", "to eat"),
                ch("药", "yào", "medicine"),
                ch("。", ".", "."),
                ch("她", "tā", "she"),
                ch("自", "zì", "self"),
                ch("己", "jǐ", "self"),
                ch("吃", "chī", "to eat"),
                ch("了", "le", "completed"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("她", "tā", "she"),
                ch("飞", "fēi", "to fly"),
                ch("到", "dào", "to"),
                ch("了", "le", "completed"),
                ch("月", "yuè", "moon"),
                ch("亮", "liang", "moon"),
                ch("上", "shàng", "above"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("后", "Hòu", "Hou Yi"),
                ch("羿", "Yì", "Hou Yi"),
                ch("很", "hěn", "very"),
                ch("想", "xiǎng", "to miss"),
                ch("她", "tā", "her"),
                ch("。", ".", "."),
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("八", "bā", "eight"),
                ch("月", "yuè", "month"),
                ch("十", "shí", "ten"),
                ch("五", "wǔ", "five"),
                ch("日", "rì", "day"),
                ch("，", ",", ","),
                ch("他", "tā", "he"),
                ch("看", "kàn", "to look at"),
                ch("月", "yuè", "moon"),
                ch("亮", "liang", "moon"),
                ch("，", ",", ","),
                ch("想", "xiǎng", "to miss"),
                ch("嫦", "Cháng", "Chang'e"),
                ch("娥", "é", "Chang'e"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("现", "xiàn", "now"),
                ch("在", "zài", "now"),
                ch("，", ",", ","),
                ch("人", "rén", "people"),
                ch("们", "men", "plural"),
                ch("每", "měi", "every"),
                ch("年", "nián", "year"),
                ch("八", "bā", "eight"),
                ch("月", "yuè", "month"),
                ch("十", "shí", "ten"),
                ch("五", "wǔ", "five"),
                ch("日", "rì", "day"),
                ch("都", "dōu", "all"),
                ch("一", "yì", "together"),
                ch("起", "qǐ", "together"),
                ch("看", "kàn", "to look at"),
                ch("月", "yuè", "moon"),
                ch("亮", "liang", "moon"),
                ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_three_body_1() -> Story {
    Story {
        id: 6,
        title: p("The Three-Body Problem"),
        title_cn: p("三体"),
        description: p("First book of the Three-Body Problem trilogy. A secret message from an alien civilization threatens humanity."),
        extra_vocab: vec![
            extra("三体", "sān tǐ", "three-body (physics problem)"),
            extra("外星", "wài xīng", "alien, extraterrestrial"),
            extra("文明", "wén míng", "civilization"),
            extra("威胁", "wēi xié", "threat"),
            extra("物理", "wù lǐ", "physics"),
            extra("科学家", "kē xué jiā", "scientist"),
            extra("游戏", "yóu xì", "game"),
            extra("虚拟", "xū nǐ", "virtual"),
            extra("现实", "xiàn shí", "reality"),
            extra("毁灭", "huǐ miè", "destruction"),
            extra("宇宙", "yǔ zhòu", "universe"),
            extra("飞船", "fēi chuán", "spaceship"),
            extra("纳米", "nà mǐ", "nano"),
            extra("技术", "jì shù", "technology"),
            extra("危机", "wēi jī", "crisis"),
            extra("人类", "rén lèi", "humanity"),
            extra("未来", "wèi lái", "future"),
            extra("秘密", "mì mì", "secret"),
            extra("组织", "zǔ zhī", "organization"),
            extra("革命", "gé mìng", "revolution"),
        ],
        paragraphs: vec![
            para(vec![
                ch("在", "zài", "in"), ch("中", "zhōng", "China"), ch("国", "guó", "country"),
                ch("文", "wén", "cultural"), ch("化", "huà", "revolution"), ch("大", "dà", "great"),
                ch("革", "gé", "revolution"), ch("命", "mìng", "revolution"), ch("时", "shí", "time"),
                ch("代", "dài", "era"), ch("，", ",", ","), ch("一", "yī", "one"), ch("位", "wèi", "measure word"),
                ch("年", "nián", "year"), ch("轻", "qīng", "young"), ch("女", "nǚ", "female"),
                ch("物", "wù", "physics"), ch("理", "lǐ", "physics"), ch("学", "xué", "study"),
                ch("家", "jiā", "person"), ch("叶", "Yè", "Ye"), ch("文", "Wén", "Wen"),
                ch("洁", "jié", "clean/pure"), ch("参", "cān", "participate"), ch("加", "jiā", "participate"),
                ch("了", "le", "particle"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("秘", "mì", "secret"), ch("密", "mì", "secret"), ch("的", "de", "possessive"),
                ch("项", "xiàng", "project"), ch("目", "mù", "project"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"), ch("项", "xiàng", "project"),
                ch("目", "mù", "project"), ch("叫", "jiào", "called"), ch("红", "hóng", "red"),
                ch("岸", "àn", "shore"), ch("基", "jī", "base"), ch("地", "dì", "ground"),
                ch("，", ",", ","), ch("是", "shì", "is"), ch("中", "zhōng", "China"), ch("国", "guó", "country"),
                ch("政", "zhèng", "government"), ch("府", "fǔ", "government"), ch("试", "shì", "try"),
                ch("图", "tú", "attempt"), ch("联", "lián", "connect"), ch("系", "xì", "connect"),
                ch("外", "wài", "outside"), ch("星", "xīng", "star"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("的", "de", "possessive"), ch("秘", "mì", "secret"),
                ch("密", "mì", "secret"), ch("计", "jì", "plan"), ch("划", "huà", "plan"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("叶", "Yè", "Ye"), ch("文", "Wén", "Wen"), ch("洁", "jié", "clean/pure"),
                ch("和", "hé", "and"), ch("她", "tā", "she"), ch("的", "de", "possessive"),
                ch("男", "nán", "male"), ch("朋", "péng", "friend"), ch("友", "yǒu", "friend"),
                ch("白", "Bái", "Bai"), ch("冰", "Bīng", "Bing"), ch("一", "yī", "together"),
                ch("起", "qǐ", "together"), ch("使", "shǐ", "use"), ch("用", "yòng", "use"),
                ch("电", "diàn", "electric"), ch("波", "bō", "wave"), ch("向", "xiàng", "towards"),
                ch("太", "tài", "sun"), ch("阳", "yáng", "sun"), ch("系", "xì", "system"),
                ch("统", "tǒng", "system"), ch("发", "fā", "send"), ch("送", "sòng", "send"),
                ch("信", "xìn", "message"), ch("号", "hào", "signal"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"), ch("们", "men", "plural"), ch("的", "de", "possessive"),
                ch("目", "mù", "goal"), ch("标", "biāo", "target"), ch("是", "shì", "is"),
                ch("找", "zhǎo", "find"), ch("到", "dào", "arrive"), ch("类", "lèi", "similar"),
                ch("似", "sì", "similar"), ch("地", "dì", "earth"), ch("球", "qiú", "ball"),
                ch("的", "de", "possessive"), ch("行", "xíng", "planet"), ch("星", "xīng", "star"),
                ch("，", ",", ","), ch("希", "xī", "hope"), ch("望", "wàng", "hope"),
                ch("建", "jiàn", "establish"), ch("立", "lì", "establish"), ch("联", "lián", "alliance"),
                ch("盟", "méng", "alliance"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("但", "dàn", "but"), ch("是", "shì", "is"), ch("，", ",", ","), ch("他", "tā", "he"),
                ch("们", "men", "plural"), ch("不", "bù", "not"), ch("知", "zhī", "know"),
                ch("道", "dào", "know"), ch("这", "zhè", "this"), ch("个", "gè", "measure word"),
                ch("信", "xìn", "signal"), ch("号", "hào", "signal"), ch("会", "huì", "will"),
                ch("带", "dài", "bring"), ch("来", "lái", "come"), ch("巨", "jù", "huge"),
                ch("大", "dà", "great"), ch("的", "de", "possessive"), ch("危", "wēi", "danger"),
                ch("机", "jī", "crisis"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("四", "sì", "four"), ch("十", "shí", "ten"), ch("年", "nián", "year"),
                ch("后", "hòu", "after"), ch("，", ",", ","), ch("叶", "Yè", "Ye"),
                ch("文", "Wén", "Wen"), ch("洁", "jié", "clean/pure"), ch("已", "yǐ", "already"),
                ch("经", "jīng", "already"), ch("成", "chéng", "become"), ch("为", "wéi", "become"),
                ch("一", "yī", "one"), ch("位", "wèi", "measure word"), ch("著", "zhù", "famous"),
                ch("名", "míng", "famous"), ch("物", "wù", "physics"), ch("理", "lǐ", "physics"),
                ch("学", "xué", "study"), ch("家", "jiā", "person"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("一", "yī", "one"), ch("天", "tiān", "day"), ch("，", ",", ","), ch("她", "tā", "she"),
                ch("接", "jiē", "receive"), ch("到", "dào", "receive"), ch("了", "le", "particle"),
                ch("一", "yī", "one"), ch("个", "gè", "measure word"), ch("神", "shén", "mysterious"),
                ch("秘", "mì", "mysterious"), ch("的", "de", "possessive"), ch("游", "yóu", "game"),
                ch("戏", "xì", "game"), ch("邀", "yāo", "invite"), ch("请", "qǐng", "invite"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"), ch("游", "yóu", "game"),
                ch("戏", "xì", "game"), ch("叫", "jiào", "called"), ch("三", "sān", "three"),
                ch("体", "tǐ", "body"), ch("，", ",", ","), ch("是", "shì", "is"), ch("一", "yī", "one"),
                ch("个", "gè", "measure word"), ch("虚", "xū", "virtual"), ch("拟", "nǐ", "virtual"),
                ch("现", "xiàn", "reality"), ch("实", "shí", "reality"), ch("游", "yóu", "game"),
                ch("戏", "xì", "game"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("游", "yóu", "game"), ch("戏", "xì", "game"),
                ch("里", "lǐ", "inside"), ch("，", ",", ","), ch("球", "qiú", "player"),
                ch("员", "yuán", "player"), ch("们", "men", "plural"), ch("可", "kě", "can"),
                ch("以", "yǐ", "can"), ch("经", "jīng", "experience"), ch("历", "lì", "experience"),
                ch("古", "gǔ", "ancient"), ch("代", "dài", "ancient"), ch("中", "zhōng", "China"),
                ch("国", "guó", "country"), ch("的", "de", "possessive"), ch("历", "lì", "history"),
                ch("史", "shǐ", "history"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("叶", "Yè", "Ye"), ch("文", "Wén", "Wen"), ch("洁", "jié", "clean/pure"),
                ch("发", "fā", "discover"), ch("现", "xiàn", "discover"), ch("这", "zhè", "this"),
                ch("个", "gè", "measure word"), ch("游", "yóu", "game"), ch("戏", "xì", "game"),
                ch("竟", "jìng", "actually"), ch("然", "rán", "actually"), ch("是", "shì", "is"),
                ch("真", "zhēn", "real"), ch("实", "shí", "real"), ch("的", "de", "possessive"),
                ch("外", "wài", "alien"), ch("星", "xīng", "alien"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("在", "zài", "in"), ch("控", "kòng", "control"),
                ch("制", "zhì", "control"), ch("！", "!", "!"),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("来", "lái", "come"), ch("自", "zì", "from"),
                ch("一", "yī", "one"), ch("个", "gè", "measure word"), ch("叫", "jiào", "called"),
                ch("三", "sān", "three"), ch("体", "tǐ", "three"), ch("星", "xīng", "star"),
                ch("系", "xì", "system"), ch("的", "de", "possessive"), ch("行", "xíng", "planet"),
                ch("星", "xīng", "star"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("那", "nà", "that"), ch("里", "lǐ", "there"),
                ch("，", ",", ","), ch("三", "sān", "three"), ch("个", "gè", "three"),
                ch("太", "tài", "sun"), ch("阳", "yáng", "sun"), ch("让", "ràng", "make"),
                ch("行", "xíng", "planet"), ch("星", "xīng", "star"), ch("轨", "guǐ", "orbit"),
                ch("道", "dào", "orbit"), ch("不", "bù", "not"), ch("稳", "wěn", "stable"),
                ch("定", "dìng", "stable"), ch("，", ",", ","), ch("生", "shēng", "life"),
                ch("活", "huó", "life"), ch("环", "huán", "environment"), ch("境", "jìng", "environment"),
                ch("非", "fēi", "extremely"), ch("常", "cháng", "extremely"), ch("恶", "è", "harsh"),
                ch("劣", "liè", "harsh"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("决", "jué", "decide"), ch("定", "dìng", "decide"),
                ch("迁", "qiān", "migrate"), ch("移", "yí", "migrate"), ch("到", "dào", "to"),
                ch("地", "dì", "earth"), ch("球", "qiú", "earth"), ch("，", ",", ","),
                ch("因", "yīn", "because"), ch("为", "wéi", "because"), ch("他", "tā", "they"),
                ch("们", "men", "plural"), ch("认", "rèn", "believe"), ch("为", "wéi", "believe"),
                ch("地", "dì", "earth"), ch("球", "qiú", "earth"), ch("是", "shì", "is"),
                ch("一", "yī", "one"), ch("个", "gè", "measure word"), ch("理", "lǐ", "ideal"),
                ch("想", "xiǎng", "ideal"), ch("的", "de", "possessive"), ch("新", "xīn", "new"),
                ch("家", "jiā", "home"), ch("园", "yuán", "garden"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("叶", "Yè", "Ye"), ch("文", "Wén", "Wen"), ch("洁", "jié", "clean/pure"),
                ch("成", "chéng", "become"), ch("为", "wéi", "become"), ch("联", "lián", "connect"),
                ch("系", "xì", "connect"), ch("外", "wài", "alien"), ch("星", "xīng", "alien"),
                ch("人", "rén", "people"), ch("的", "de", "possessive"), ch("关", "guān", "key"),
                ch("键", "jiàn", "key"), ch("人", "rén", "person"), ch("物", "wù", "person"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("她", "tā", "she"), ch("必", "bì", "must"), ch("须", "xū", "must"),
                ch("帮", "bāng", "help"), ch("助", "zhù", "help"), ch("外", "wài", "alien"),
                ch("星", "xīng", "alien"), ch("人", "rén", "people"), ch("解", "jiě", "solve"),
                ch("决", "jué", "solve"), ch("三", "sān", "three"), ch("体", "tǐ", "body"),
                ch("问", "wèn", "problem"), ch("题", "tí", "problem"), ch("，", ",", ","),
                ch("才", "cái", "only then"), ch("能", "néng", "can"), ch("获", "huò", "obtain"),
                ch("得", "dé", "obtain"), ch("他", "tā", "they"), ch("们", "men", "plural"),
                ch("的", "de", "possessive"), ch("信", "xìn", "trust"), ch("任", "rèn", "trust"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("与", "yǔ", "with"), ch("此", "cǐ", "this"), ch("同", "tóng", "same"),
                ch("时", "shí", "time"), ch("，", ",", ","), ch("地", "dì", "earth"), ch("球", "qiú", "earth"),
                ch("上", "shàng", "on"), ch("的", "de", "possessive"), ch("科", "kē", "science"),
                ch("学", "xué", "science"), ch("家", "jiā", "person"), ch("们", "men", "plural"),
                ch("开", "kāi", "start"), ch("始", "shǐ", "start"), ch("意", "yì", "realize"),
                ch("识", "shí", "realize"), ch("到", "dào", "realize"), ch("这", "zhè", "this"),
                ch("个", "gè", "measure word"), ch("威", "wēi", "threat"), ch("胁", "xié", "threat"),
                ch("的", "de", "possessive"), ch("严", "yán", "serious"), ch("重", "zhòng", "serious"),
                ch("性", "xìng", "nature"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "they"), ch("们", "men", "plural"), ch("形", "xíng", "form"),
                ch("成", "chéng", "form"), ch("了", "le", "particle"), ch("一", "yī", "one"),
                ch("个", "gè", "measure word"), ch("秘", "mì", "secret"), ch("密", "mì", "secret"),
                ch("组", "zǔ", "group"), ch("织", "zhī", "organization"), ch("，", ",", ","),
                ch("叫", "jiào", "called"), ch("面", "miàn", "face"), ch("壁", "bì", "wall"),
                ch("计", "jì", "plan"), ch("划", "huà", "plan"), ch("，", ",", ","),
                ch("准", "zhǔn", "prepare"), ch("备", "bèi", "prepare"), ch("应", "yìng", "respond"),
                ch("对", "duì", "respond"), ch("外", "wài", "alien"), ch("星", "xīng", "alien"),
                ch("人", "rén", "people"), ch("的", "de", "possessive"), ch("侵", "qīn", "invasion"),
                ch("略", "lüè", "invasion"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("整", "zhěng", "whole"), ch("个", "gè", "whole"), ch("故", "gù", "story"),
                ch("事", "shì", "story"), ch("充", "chōng", "full"), ch("满", "mǎn", "full"),
                ch("了", "le", "particle"), ch("科", "kē", "science"), ch("学", "xué", "science"),
                ch("、", ",", ","), ch("历", "lì", "history"), ch("史", "shǐ", "history"),
                ch("和", "hé", "and"), ch("哲", "zhé", "philosophy"), ch("学", "xué", "philosophy"),
                ch("的", "de", "possessive"), ch("探", "tàn", "exploration"), ch("索", "suǒ", "exploration"),
                ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_three_body_2() -> Story {
    Story {
        id: 7,
        title: p("The Dark Forest"),
        title_cn: p("黑暗森林"),
        description: p("Second book of the Three-Body Problem trilogy. Humanity discovers the dark forest theory and prepares for interstellar war."),
        extra_vocab: vec![
            extra("黑暗森林", "hēi àn sēn lín", "dark forest (theory)"),
            extra("理论", "lǐ lùn", "theory"),
            extra("星际", "xīng jì", "interstellar"),
            extra("战争", "zhàn zhēng", "war"),
            extra("探测器", "tàn cè qì", "probe"),
            extra("舰队", "jiàn duì", "fleet"),
            extra("智子", "zhì zǐ", "sophon (intelligent particle)"),
            extra("监控", "jiān kòng", "monitor"),
            extra("战略", "zhàn lüè", "strategy"),
            extra("联盟", "lián méng", "alliance"),
            extra("逃亡", "táo wáng", "escape"),
            extra("末日", "mò rì", "doomsday"),
            extra("审判", "shěn pàn", "judgment"),
            extra("进化", "jìn huà", "evolution"),
            extra("生存", "shēng cún", "survival"),
            extra("智慧", "zhì huì", "wisdom"),
            extra("和平", "hé píng", "peace"),
            extra("征服", "zhēng fú", "conquer"),
            extra("毁灭", "huǐ miè", "destruction"),
            extra("希望", "xī wàng", "hope"),
            extra("绝望", "jué wàng", "despair"),
        ],
        paragraphs: vec![
            para(vec![
                ch("第", "dì", "second"), ch("二", "èr", "book"), ch("部", "bù", "part"),
                ch("故", "gù", "story"), ch("事", "shì", "story"), ch("从", "cóng", "from"),
                ch("罗", "Luó", "Luo"), ch("辑", "Jí", "Ji"), ch("的", "de", "possessive"),
                ch("故", "gù", "story"), ch("事", "shì", "story"), ch("开", "kāi", "start"),
                ch("始", "shǐ", "start"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("罗", "Luó", "Luo"), ch("辑", "Jí", "Ji"), ch("是", "shì", "is"),
                ch("一", "yī", "one"), ch("位", "wèi", "measure word"), ch("天", "tiān", "astronomy"),
                ch("文", "wén", "astronomy"), ch("学", "xué", "study"), ch("家", "jiā", "person"),
                ch("，", ",", ","), ch("他", "tā", "he"), ch("被", "bèi", "by"),
                ch("选", "xuǎn", "select"), ch("中", "zhōng", "select"), ch("为", "wéi", "as"),
                ch("面", "miàn", "face"), ch("壁", "bì", "wall"), ch("计", "jì", "plan"),
                ch("划", "huà", "plan"), ch("的", "de", "possessive"), ch("执", "zhí", "execute"),
                ch("行", "xíng", "execute"), ch("者", "zhě", "person"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"), ch("的", "de", "possessive"), ch("任", "rèn", "duty"),
                ch("务", "wù", "duty"), ch("是", "shì", "is"), ch("想", "xiǎng", "think"),
                ch("出", "chū", "out"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("战", "zhàn", "battle"), ch("略", "lüè", "strategy"), ch("，", ",", ","),
                ch("让", "ràng", "make"), ch("人", "rén", "human"), ch("类", "lèi", "humanity"),
                ch("在", "zài", "in"), ch("星", "xīng", "interstellar"), ch("际", "jì", "interstellar"),
                ch("战", "zhàn", "war"), ch("争", "zhēng", "war"), ch("中", "zhōng", "in"),
                ch("取", "qǔ", "obtain"), ch("得", "dé", "obtain"), ch("胜", "shèng", "victory"),
                ch("利", "lì", "victory"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("罗", "Luó", "Luo"), ch("辑", "Jí", "Ji"), ch("发", "fā", "discover"),
                ch("现", "xiàn", "discover"), ch("了", "le", "particle"), ch("宇", "yǔ", "universe"),
                ch("宙", "zhòu", "universe"), ch("社", "shè", "society"), ch("会", "huì", "society"),
                ch("的", "de", "possessive"), ch("真", "zhēn", "true"), ch("实", "shí", "true"),
                ch("本", "běn", "nature"), ch("质", "zhì", "nature"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"),
                ch("中", "zhōng", "in"), ch("，", ",", ","), ch("每", "měi", "every"),
                ch("个", "gè", "every"), ch("文", "wén", "civilization"), ch("明", "míng", "civilization"),
                ch("都", "dōu", "all"), ch("像", "xiàng", "like"), ch("黑", "hēi", "dark"),
                ch("暗", "àn", "dark"), ch("森", "sēn", "forest"), ch("林", "lín", "forest"),
                ch("里", "lǐ", "in"), ch("的", "de", "possessive"), ch("猎", "liè", "hunter"),
                ch("人", "rén", "hunter"), ch("一", "yī", "same"), ch("样", "yàng", "same"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "they"), ch("们", "men", "plural"), ch("不", "bù", "not"),
                ch("知", "zhī", "know"), ch("道", "dào", "know"), ch("别", "bié", "other"),
                ch("人", "rén", "people"), ch("的", "de", "possessive"), ch("位", "wèi", "position"),
                ch("置", "zhì", "position"), ch("，", ",", ","), ch("但", "dàn", "but"),
                ch("又", "yòu", "also"), ch("担", "dān", "worry"), ch("心", "xīn", "worry"),
                ch("被", "bèi", "by"), ch("别", "bié", "other"), ch("人", "rén", "people"),
                ch("发", "fā", "discover"), ch("现", "xiàn", "discover"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("所", "suǒ", "so"), ch("以", "yǐ", "so"), ch("，", ",", ","), ch("每", "měi", "every"),
                ch("个", "gè", "every"), ch("文", "wén", "civilization"), ch("明", "míng", "civilization"),
                ch("都", "dōu", "all"), ch("会", "huì", "will"), ch("主", "zhǔ", "actively"),
                ch("动", "dòng", "actively"), ch("消", "xiāo", "destroy"), ch("灭", "miè", "destroy"),
                ch("其", "qí", "other"), ch("他", "tā", "other"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("，", ",", ","), ch("以", "yǐ", "in order to"),
                ch("保", "bǎo", "protect"), ch("护", "hù", "protect"), ch("自", "zì", "own"),
                ch("己", "jǐ", "own"), ch("的", "de", "possessive"), ch("安", "ān", "safety"),
                ch("全", "quán", "safety"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("就", "jiù", "precisely"), ch("是", "shì", "is"),
                ch("黑", "hēi", "dark"), ch("暗", "àn", "dark"), ch("森", "sēn", "forest"),
                ch("林", "lín", "forest"), ch("理", "lǐ", "theory"), ch("论", "lùn", "theory"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("罗", "Luó", "Luo"), ch("辑", "Jí", "Ji"), ch("决", "jué", "decide"),
                ch("定", "dìng", "decide"), ch("公", "gōng", "public"), ch("开", "kāi", "public"),
                ch("这", "zhè", "this"), ch("个", "gè", "measure word"), ch("理", "lǐ", "theory"),
                ch("论", "lùn", "theory"), ch("，", ",", ","), ch("希", "xī", "hope"),
                ch("望", "wàng", "hope"), ch("震", "zhèn", "shock"), ch("撼", "hàn", "shock"),
                ch("全", "quán", "whole"), ch("世", "shì", "world"), ch("界", "jiè", "world"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("与", "yǔ", "with"), ch("此", "cǐ", "this"), ch("同", "tóng", "same"),
                ch("时", "shí", "time"), ch("，", ",", ","), ch("三", "sān", "three"),
                ch("体", "tǐ", "three"), ch("舰", "jiàn", "fleet"), ch("队", "duì", "fleet"),
                ch("已", "yǐ", "already"), ch("经", "jīng", "already"), ch("出", "chū", "depart"),
                ch("发", "fā", "depart"), ch("，", ",", ","), ch("正", "zhèng", "currently"),
                ch("在", "zài", "currently"), ch("向", "xiàng", "towards"), ch("地", "dì", "earth"),
                ch("球", "qiú", "earth"), ch("飞", "fēi", "fly"), ch("来", "lái", "come"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("人", "rén", "human"), ch("类", "lèi", "humanity"), ch("必", "bì", "must"),
                ch("须", "xū", "must"), ch("准", "zhǔn", "prepare"), ch("备", "bèi", "prepare"),
                ch("一", "yī", "one"), ch("场", "chǎng", "field"), ch("史", "shǐ", "historical"),
                ch("诗", "shī", "epic"), ch("般", "bān", "like"), ch("的", "de", "possessive"),
                ch("战", "zhàn", "battle"), ch("争", "zhēng", "battle"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("章", "Zhāng", "Zhang"), ch("北海", "Běi hǎi", "Beihai"), ch("是", "shì", "is"),
                ch("一", "yī", "one"), ch("位", "wèi", "measure word"), ch("军", "jūn", "military"),
                ch("事", "shì", "military"), ch("策", "cè", "strategy"), ch("略", "lüè", "strategy"),
                ch("家", "jiā", "person"), ch("，", ",", ","), ch("他", "tā", "he"),
                ch("成", "chéng", "become"), ch("为", "wéi", "become"), ch("面", "miàn", "face"),
                ch("壁", "bì", "wall"), ch("计", "jì", "plan"), ch("划", "huà", "plan"),
                ch("的", "de", "possessive"), ch("第", "dì", "second"), ch("二", "èr", "second"),
                ch("位", "wèi", "measure word"), ch("执", "zhí", "execute"), ch("行", "xíng", "execute"),
                ch("者", "zhě", "person"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"), ch("的", "de", "possessive"), ch("战", "zhàn", "battle"),
                ch("略", "lüè", "strategy"), ch("是", "shì", "is"), ch("建", "jiàn", "build"),
                ch("造", "zào", "build"), ch("一", "yī", "one"), ch("支", "zhī", "branch"),
                ch("强", "qiáng", "strong"), ch("大", "dà", "strong"), ch("的", "de", "possessive"),
                ch("宇", "yǔ", "space"), ch("宙", "zhòu", "space"), ch("舰", "jiàn", "fleet"),
                ch("队", "duì", "fleet"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("泰", "Tài", "Tai"), ch("勒", "Lè", "Le"), ch("是", "shì", "is"),
                ch("第", "dì", "third"), ch("三", "sān", "third"), ch("位", "wèi", "measure word"),
                ch("面", "miàn", "face"), ch("壁", "bì", "wall"), ch("者", "zhě", "person"),
                ch("，", ",", ","), ch("他", "tā", "he"), ch("是", "shì", "is"), ch("一", "yī", "one"),
                ch("位", "wèi", "measure word"), ch("社", "shè", "social"), ch("会", "huì", "social"),
                ch("学", "xué", "study"), ch("家", "jiā", "person"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("他", "tā", "he"), ch("相", "xiāng", "believe"), ch("信", "xìn", "believe"),
                ch("人", "rén", "human"), ch("类", "lèi", "humanity"), ch("的", "de", "possessive"),
                ch("希", "xī", "hope"), ch("望", "wàng", "hope"), ch("在", "zài", "lies in"),
                ch("于", "yú", "lies in"), ch("精", "jīng", "spiritual"), ch("神", "shén", "spiritual"),
                ch("力", "lì", "power"), ch("量", "liàng", "power"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("智", "zhì", "intelligent"), ch("子", "zǐ", "particle"), ch("是", "shì", "is"),
                ch("三", "sān", "three"), ch("体", "tǐ", "three"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("发", "fā", "send"), ch("送", "sòng", "send"),
                ch("来", "lái", "come"), ch("的", "de", "possessive"), ch("超", "chāo", "super"),
                ch("级", "jí", "level"), ch("监", "jiān", "monitor"), ch("控", "kòng", "monitor"),
                ch("器", "qì", "device"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("它", "tā", "it"), ch("们", "men", "plural"), ch("能", "néng", "can"),
                ch("监", "jiān", "monitor"), ch("视", "shì", "monitor"), ch("和", "hé", "and"),
                ch("干", "gān", "interfere"), ch("预", "yù", "interfere"), ch("整", "zhěng", "whole"),
                ch("个", "gè", "whole"), ch("地", "dì", "earth"), ch("球", "qiú", "earth"),
                ch("的", "de", "possessive"), ch("科", "kē", "science"), ch("学", "xué", "science"),
                ch("发", "fā", "development"), ch("展", "zhǎn", "development"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("人", "rén", "human"), ch("类", "lèi", "humanity"), ch("的", "de", "possessive"),
                ch("每", "měi", "every"), ch("一", "yī", "every"), ch("个", "gè", "every"),
                ch("动", "dòng", "action"), ch("作", "zuò", "action"), ch("都", "dōu", "all"),
                ch("在", "zài", "under"), ch("智", "zhì", "intelligent"), ch("子", "zǐ", "particle"),
                ch("的", "de", "possessive"), ch("监", "jiān", "surveillance"), ch("视", "shì", "surveillance"),
                ch("之", "zhī", "under"), ch("下", "xià", "under"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("面", "miàn", "face"), ch("壁", "bì", "wall"), ch("计", "jì", "plan"),
                ch("划", "huà", "plan"), ch("的", "de", "possessive"), ch("成", "chéng", "success"),
                ch("功", "gōng", "success"), ch("取", "qǔ", "depend on"), ch("决", "jué", "depend on"),
                ch("于", "yú", "depend on"), ch("这", "zhè", "this"), ch("四", "sì", "four"),
                ch("位", "wèi", "measure word"), ch("面", "miàn", "face"), ch("壁", "bì", "wall"),
                ch("者", "zhě", "person"), ch("的", "de", "possessive"), ch("智", "zhì", "wisdom"),
                ch("慧", "huì", "wisdom"), ch("和", "hé", "and"), ch("勇", "yǒng", "courage"),
                ch("气", "qì", "courage"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("故", "gù", "story"), ch("事", "shì", "story"), ch("探", "tàn", "explore"),
                ch("索", "suǒ", "explore"), ch("了", "le", "particle"), ch("宇", "yǔ", "universe"),
                ch("宙", "zhòu", "universe"), ch("的", "de", "possessive"), ch("深", "shēn", "deep"),
                ch("层", "céng", "layer"), ch("秘", "mì", "mystery"), ch("密", "mì", "mystery"),
                ch("，", ",", ","), ch("以", "yǐ", "and"), ch("及", "jí", "and"), ch("人", "rén", "human"),
                ch("类", "lèi", "humanity"), ch("社", "shè", "society"), ch("会", "huì", "society"),
                ch("的", "de", "possessive"), ch("复", "fù", "complex"), ch("杂", "zá", "complex"),
                ch("性", "xìng", "nature"), ch("。", ".", "."),
            ]),
        ],
    }
}

fn story_three_body_3() -> Story {
    Story {
        id: 8,
        title: p("Death's End"),
        title_cn: p("死神永生"),
        description: p("Third and final book of the Three-Body Problem trilogy. The ultimate fate of humanity and the universe is revealed."),
        extra_vocab: vec![
            extra("死神永生", "sǐ shén yǒng shēng", "Death's End"),
            extra("维度", "wéi dù", "dimension"),
            extra("降维", "jiàng wéi", "dimensionality reduction"),
            extra("二向箔", "èr xiàng bó", "two-dimensional foil"),
            extra("光速", "guāng sù", "speed of light"),
            extra("黑洞", "hēi dòng", "black hole"),
            extra("奇点", "qí diǎn", "singularity"),
            extra("永恒", "yǒng héng", "eternal"),
            extra("轮回", "lún huí", "reincarnation"),
            extra("意识", "yì shí", "consciousness"),
            extra("记忆", "jì yì", "memory"),
            extra("上传", "shàng chuán", "upload"),
            extra("虚拟现实", "xū nǐ xiàn shí", "virtual reality"),
            extra("量子", "liàng zǐ", "quantum"),
            extra("时空", "shí kōng", "spacetime"),
            extra("平行宇宙", "píng xíng yǔ zhòu", "parallel universe"),
            extra("终极", "zhōng jí", "ultimate"),
            extra("审判", "shěn pàn", "judgment"),
            extra("救赎", "jiù shú", "redemption"),
            extra("超越", "chāo yuè", "transcend"),
        ],
        paragraphs: vec![
            para(vec![
                ch("第", "dì", "third"), ch("三", "sān", "book"), ch("部", "bù", "part"),
                ch("故", "gù", "story"), ch("事", "shì", "story"), ch("时", "shí", "time"),
                ch("间", "jiān", "span"), ch("跨", "kuà", "span"), ch("度", "dù", "span"),
                ch("达", "dá", "reach"), ch("到", "dào", "reach"), ch("十", "shí", "ten"),
                ch("九", "jiǔ", "nine"), ch("万", "wàn", "ten thousand"), ch("年", "nián", "year"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("这", "zhè", "this"), ch("部", "bù", "part"),
                ch("作", "zuò", "work"), ch("品", "pǐn", "work"), ch("中", "zhōng", "in"),
                ch("，", ",", ","), ch("作", "zuò", "author"), ch("者", "zhě", "author"),
                ch("探", "tàn", "explore"), ch("索", "suǒ", "explore"), ch("了", "le", "particle"),
                ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"), ch("的", "de", "possessive"),
                ch("终", "zhōng", "ultimate"), ch("极", "jí", "ultimate"), ch("命", "mìng", "fate"),
                ch("运", "yùn", "fate"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("云", "Yún", "Yun"), ch("天", "Tiān", "Tian"), ch("明", "Míng", "Ming"),
                ch("是", "shì", "is"), ch("一", "yī", "one"), ch("位", "wèi", "measure word"),
                ch("古", "gǔ", "ancient"), ch("代", "dài", "ancient"), ch("诗", "shī", "poet"),
                ch("人", "rén", "poet"), ch("，", ",", ","), ch("他", "tā", "he"),
                ch("的", "de", "possessive"), ch("意", "yì", "consciousness"), ch("识", "shí", "consciousness"),
                ch("被", "bèi", "by"), ch("上", "shàng", "upload"), ch("传", "chuán", "upload"),
                ch("到", "dào", "to"), ch("了", "le", "particle"), ch("一", "yī", "one"),
                ch("个", "gè", "measure word"), ch("虚", "xū", "virtual"), ch("拟", "nǐ", "virtual"),
                ch("现", "xiàn", "reality"), ch("实", "shí", "reality"), ch("世", "shì", "world"),
                ch("界", "jiè", "world"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("那", "nà", "that"), ch("里", "lǐ", "there"),
                ch("，", ",", ","), ch("时", "shí", "time"), ch("间", "jiān", "time"),
                ch("可", "kě", "can"), ch("以", "yǐ", "can"), ch("倒", "dào", "reverse"),
                ch("流", "liú", "reverse"), ch("，", ",", ","), ch("他", "tā", "he"),
                ch("能", "néng", "can"), ch("重", "chóng", "re"), ch("新", "xīn", "re"),
                ch("体", "tǐ", "experience"), ch("验", "yàn", "experience"), ch("历", "lì", "experience"),
                ch("史", "shǐ", "history"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("希", "Xī", "Xi"), ch("拉", "Lā", "La"), ch("是", "shì", "is"),
                ch("一", "yī", "one"), ch("位", "wèi", "measure word"), ch("宇", "yǔ", "space"),
                ch("宙", "zhòu", "space"), ch("航", "háng", "navigation"), ch("行", "xíng", "navigation"),
                ch("员", "yuán", "person"), ch("，", ",", ","), ch("她", "tā", "she"),
                ch("的", "de", "possessive"), ch("飞", "fēi", "spacecraft"), ch("船", "chuán", "spacecraft"),
                ch("被", "bèi", "by"), ch("二", "èr", "two"), ch("向", "xiàng", "dimensional"),
                ch("箔", "bó", "foil"), ch("攻", "gōng", "attack"), ch("击", "jī", "attack"),
                ch("，", ",", ","), ch("整", "zhěng", "whole"), ch("个", "gè", "whole"),
                ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"), ch("的", "de", "possessive"),
                ch("维", "wéi", "dimension"), ch("度", "dù", "dimension"), ch("被", "bèi", "by"),
                ch("降", "jiàng", "reduce"), ch("低", "dī", "reduce"), ch("了", "le", "particle"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("二", "èr", "two"), ch("向", "xiàng", "dimensional"), ch("箔", "bó", "foil"),
                ch("是", "shì", "is"), ch("一", "yī", "one"), ch("种", "zhǒng", "kind"),
                ch("超", "chāo", "super"), ch("级", "jí", "level"), ch("武", "wǔ", "weapon"),
                ch("器", "qì", "weapon"), ch("，", ",", ","), ch("它", "tā", "it"),
                ch("能", "néng", "can"), ch("让", "ràng", "make"), ch("三", "sān", "three"),
                ch("维", "wéi", "dimensional"), ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"),
                ch("变", "biàn", "become"), ch("成", "chéng", "become"), ch("二", "èr", "two"),
                ch("维", "wéi", "dimensional"), ch("的", "de", "possessive"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("二", "èr", "two"), ch("维", "wéi", "dimensional"),
                ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"), ch("中", "zhōng", "in"),
                ch("，", ",", ","), ch("物", "wù", "matter"), ch("质", "zhì", "matter"),
                ch("会", "huì", "will"), ch("平", "píng", "flatten"), ch("铺", "pū", "flatten"),
                ch("开", "kāi", "flatten"), ch("来", "lái", "come"), ch("，", ",", ","),
                ch("生", "shēng", "life"), ch("命", "mìng", "life"), ch("不", "bù", "cannot"),
                ch("可", "kě", "cannot"), ch("能", "néng", "cannot"), ch("存", "cún", "exist"),
                ch("在", "zài", "exist"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("人", "rén", "human"), ch("类", "lèi", "humanity"), ch("文", "wén", "civilization"),
                ch("明", "míng", "civilization"), ch("面", "miàn", "face"), ch("临", "lín", "face"),
                ch("着", "zhe", "facing"), ch("最", "zuì", "most"), ch("终", "zhōng", "ultimate"),
                ch("极", "jí", "ultimate"), ch("的", "de", "possessive"), ch("威", "wēi", "threat"),
                ch("胁", "xié", "threat"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("程", "Chéng", "Cheng"), ch("心", "Xīn", "Xin"), ch("是", "shì", "is"),
                ch("一", "yī", "one"), ch("位", "wèi", "measure word"), ch("年", "nián", "young"),
                ch("轻", "qīng", "young"), ch("的", "de", "possessive"), ch("宇", "yǔ", "space"),
                ch("宙", "zhòu", "space"), ch("社", "shè", "social"), ch("会", "huì", "social"),
                ch("学", "xué", "study"), ch("家", "jiā", "person"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("她", "tā", "she"), ch("参", "cān", "participate"), ch("加", "jiā", "participate"),
                ch("了", "le", "particle"), ch("一", "yī", "one"), ch("个", "gè", "measure word"),
                ch("时", "shí", "time"), ch("空", "kōng", "space"), ch("旅", "lǚ", "travel"),
                ch("行", "xíng", "travel"), ch("项", "xiàng", "project"), ch("目", "mù", "project"),
                ch("，", ",", ","), ch("见", "jiàn", "see"), ch("证", "zhèng", "witness"),
                ch("了", "le", "particle"), ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"),
                ch("的", "de", "possessive"), ch("多", "duō", "multiple"), ch("种", "zhǒng", "multiple"),
                ch("可", "kě", "possible"), ch("能", "néng", "possible"), ch("性", "xìng", "possibility"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("故", "gù", "story"), ch("事", "shì", "story"), ch("探", "tàn", "explore"),
                ch("索", "suǒ", "explore"), ch("了", "le", "particle"), ch("意", "yì", "consciousness"),
                ch("识", "shí", "consciousness"), ch("的", "de", "possessive"), ch("本", "běn", "nature"),
                ch("质", "zhì", "nature"), ch("，", ",", ","), ch("以", "yǐ", "and"), ch("及", "jí", "and"),
                ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"), ch("的", "de", "possessive"),
                ch("终", "zhōng", "ultimate"), ch("极", "jí", "ultimate"), ch("秘", "mì", "mystery"),
                ch("密", "mì", "mystery"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("在", "zài", "in"), ch("小", "xiǎo", "small"), ch("说", "shuō", "say"),
                ch("的", "de", "possessive"), ch("结", "jié", "end"), ch("尾", "wěi", "end"),
                ch("，", ",", ","), ch("作", "zuò", "author"), ch("者", "zhě", "author"),
                ch("描", "miáo", "describe"), ch("述", "shù", "describe"), ch("了", "le", "particle"),
                ch("一", "yī", "one"), ch("个", "gè", "measure word"), ch("美", "měi", "beautiful"),
                ch("好", "hǎo", "beautiful"), ch("的", "de", "possessive"), ch("未", "wèi", "future"),
                ch("来", "lái", "future"), ch("，", ",", ","), ch("其", "qí", "where"), ch("中", "zhōng", "where"),
                ch("意", "yì", "consciousness"), ch("识", "shí", "consciousness"), ch("可", "kě", "can"),
                ch("以", "yǐ", "can"), ch("永", "yǒng", "eternal"), ch("生", "shēng", "eternal"),
                ch("。", ".", "."),
            ]),
            para(vec![
                ch("这", "zhè", "this"), ch("部", "bù", "part"), ch("作", "zuò", "work"),
                ch("品", "pǐn", "work"), ch("让", "ràng", "make"), ch("读", "dú", "reader"),
                ch("者", "zhě", "reader"), ch("深", "shēn", "deep"), ch("思", "sī", "think"),
                ch("宇", "yǔ", "universe"), ch("宙", "zhòu", "universe"), ch("的", "de", "possessive"),
                ch("意", "yì", "meaning"), ch("义", "yì", "meaning"), ch("，", ",", ","),
                ch("以", "yǐ", "and"), ch("及", "jí", "and"), ch("人", "rén", "human"),
                ch("类", "lèi", "humanity"), ch("在", "zài", "in"), ch("其", "qí", "its"),
                ch("中", "zhōng", "in"), ch("的", "de", "possessive"), ch("地", "dì", "position"),
                ch("位", "wèi", "position"), ch("。", ".", "."),
            ]),
            para(vec![
                ch("整", "zhěng", "whole"), ch("个", "gè", "whole"), ch("三", "sān", "three"),
                ch("体", "tǐ", "three"), ch("三", "sān", "three"), ch("部", "bù", "part"),
                ch("曲", "qū", "part"), ch("是", "shì", "is"), ch("科", "kē", "science"),
                ch("幻", "huàn", "fiction"), ch("文", "wén", "literature"), ch("学", "xué", "literature"),
                ch("的", "de", "possessive"), ch("巅", "diān", "peak"), ch("峰", "fēng", "peak"),
                ch("之", "zhī", "of"), ch("作", "zuò", "work"), ch("。", ".", "."),
            ]),
        ],
    }
}
